# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TestReactNative' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TestReactNative
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'

  target 'TestReactNative-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'react-native-fetch-blob', :path => '../node_modules/react-native-fetch-blob'

  end

  target 'TestReactNativeTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

